services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: geopass
      MYSQL_DATABASE: geoknowledge
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data: